### ISSUE TITLE
Prisma deploy having no effect

### ISSUE THREAD

**Issue by baptistemarchand** [prisma/datamodel-v1.1-feedback#23]
I'm currently migrating a codebase from Prisma 1.17 to 1.34 (as an intermediate step before migrating to Prisma 2) so I'm following [this guide](https://v1.prisma.io/docs/1.31/releases-and-maintenance/features-in-preview/datamodel-v11-b6a7/#upgrading-to-datamodel-v1.1).

I upgraded my Prisma server to `prismagraphql/prisma:1.34` and my Prisma client to `1.34.10`, ran the `prisma introspect` and replaced my datamodel.graphql file whith the generated one.

When I run `prisma deploy --force` I get a list of changes like this
```
...
MyEnum (Enum)
  ~ Updated enum MyEnum

MyRelation (Relation)
  - The id column `id` in link table `_MyRelation` has been removed.
    It was a Prisma legacy column that is not in use anymore.
...
``` 
as expected but it seems to have no effect on my database. If I run the same command again I get exactly the same output.
Did I miss something?

**Comment by nikolasburk** [comment]
Hey @baptistemarchand, I _believe_ the invocation of `prisma deploy` at this point is not supposed to actually change anything in the DB. It's basically just a step to "confirm" that the new datamodel is in sync with the current DB schema. Sorry that this isn't clear from the documentation.

Also, just as a general side-note, I'm not sure if it's worth it to upgrade to datamodel 1.1 before upgrading to Prisma 2. Do you have a concrete reason why you want to do that? (I guess one benefit would be to already optimize part of the DB schema, e.g. turn 1-n relations from relation tables to inline relations, but you can do that during the upgrade to Prisma 2 as well. If you do that, the Upgrade CLI will actually generate the right SQL statements for you, so it might be better to do everything in one go instead of first upgrading to datamodel 1.1).

**Comment by baptistemarchand** [comment]
Hi @nikolasburk ,
Thank you for the fast answer!
The codebase I'm working with is too large to migrate to Prisma 2 in one go so I'll need to run Prisma 1 and 2 in parallel.
My understanding is that Prisma 1.17 is not compatible with foreign key relations, and Prisma 2 is not compatible with 1-n table relations. That's why I think I need to upgrade to 1.34. Is my assumption correct?

To go back to `prisma deploy`, you're saying the behaviour changed somewhere between 1.17 and 1.34? Because we always use `prisma deploy` to modify our db. We have `migrations: true` in the `PRISMA_CONFIG` of our docker-compose. Maybe that option is not possible in 1.34?

Thanks again for you time.

**Comment by nikolasburk** [comment]
> The codebase I'm working with is too large to migrate to Prisma 2 in one go so I'll need to run Prisma 1 and 2 in parallel.
My understanding is that Prisma 1.17 is not compatible with foreign key relations, and Prisma 2 is not compatible with 1-n table relations. That's why I think I need to upgrade to 1.34. Is my assumption correct?

Got it, yeah this makes sense then! 👍 

> you're saying the behaviour changed somewhere between 1.17 and 1.34? Because we always use prisma deploy to modify our db. We have migrations: true in the PRISMA_CONFIG of our docker-compose. Maybe that option is not possible in 1.34?

Not quite... If I recall correctly from the guide, `prisma deploy` in [step 3](https://v1.prisma.io/docs/1.31/releases-and-maintenance/features-in-preview/datamodel-v11-b6a7/#3.-migrating-to-datamodel-v1.1-syntax) is executed only to _validate_ that the new datamodel syntax is now correct. 

Because after you upgraded the Prisma server from 1.17 to 1.34 you were not able to deploy the previous data model any more (e.g. because the `@id` is not used there but is now required in 1.34). That's why the guide instructs to introspect the DB so that you get a data model that adheres to the new syntax but doesn't have any actual changes with respect to the DB schema.

So if I understand you correctly and you're wondering at the end of step 3 whether `prisma deploy` should change your DB schema, then I believe that at this point the command is not supposed to change the DB schema but it's only there to validate that your new data model is now correct.

**Comment by baptistemarchand** [comment]
Ok so what I should do is look at each message in the output of `prisma deploy --force`, and try to guess the SQL command that I have to run for each?
For example I get a message "The id column `id` in link table `_MyRelation` has been removed" so it means I should manually delete the id field in SQL and then introspect again until I get no errors?

When I run `prisma deploy` (without `--force`) I get the following message :
```
Global
    ! You are migrating from the old datamodel syntax to the new one. Make sure that you understand the listed changes because the semantics are different now. Then perform the deployment with the `--force` flag.
```
which really leads me to beleive that `prisma deploy --force` is supposed to change something 🤔 .

**Comment by nikolasburk** [comment]
Ah sorry, I think I understand a bit better now what you mean, sorry that took longer on my part 🙏 

Unfortunately I haven't seen this issue before, so I'm not 100% sure what to do. Generally, there actually shouldn't be any changes listed because the new datamodel that you got from introspection is just the equivalent of the old one in the new syntax. But the underlying DB should remain the same, so it seems strange that `prisma deploy` at this point even wants to change anything. 

I'm wondering if you could just ignore these messages and just carry on with upgrade.

Can you maybe try to introduce a simple data model change (e.g. add a random model to the schema) and see if `prisma deploy` is able to apply it. If that's the case, I think you can just move on and ignore the listed changed.

**Comment by inlightmedia** [comment]
I'm seeing this same issue. It removed all the ids from my database relations.

**Comment by baptistemarchand** [comment]
@inlightmedia it's been a long time so I have no idea how I managed to get past this sorry.
Good luck!
